# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# ==================================================================================================================================
# ==================================================================================================================================

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(1107, 733)

        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1181, 741))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(28, 28))
        self.tabWidget.setObjectName("tabWidget")
        self.Dashboard = QtWidgets.QWidget()
        self.Dashboard.setObjectName("Dashboard")
        self.frame_3 = QtWidgets.QFrame(self.Dashboard)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1101, 711))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(30, 150, 321, 151))
        self.frame_2.setStyleSheet("background-color: rgb(243, 246, 249);\n"
"border-radius:10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 91))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setStyleSheet("background-color:transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../resources/note_icon.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 40, 171, 16))
        self.label_2.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(120, 60, 141, 41))
        self.label_3.setStyleSheet("color: rgb(0, 170, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.forgetButton = QtWidgets.QPushButton(self.frame_2)
        self.forgetButton.setGeometry(QtCore.QRect(70, 100, 191, 28))
        self.forgetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.forgetButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.forgetButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.forgetButton.setStyleSheet("\n"
"QPushButton {\n"
"background-color: transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(170, 170, 255);\n"
"            }\n"
"            QPushButton:hover {\n"
"           color: rgb(0, 255, 127);\n"
"            }")
        self.forgetButton.setObjectName("forgetButton")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(60, 590, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("\n"
"background: transparent; color: white; font-size: 20px;\n"
"color: rgb(170, 170, 255);")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_7.setObjectName("label_7")
        self.infolabel = QtWidgets.QLabel(self.frame_3)
        self.infolabel.setGeometry(QtCore.QRect(10, 0, 1091, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.infolabel.setFont(font)
        self.infolabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infolabel.setObjectName("infolabel")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Dashboard, icon, "")
        self.Notes = QtWidgets.QWidget()
        self.Notes.setObjectName("Notes")
        self.frame_4 = QtWidgets.QFrame(self.Notes)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1101, 711))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(60, 590, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("\n"
"background: transparent; color: white; font-size: 20px;\n"
"color: rgb(170, 170, 255);")
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_14.setObjectName("label_14")
        self.loginButton = QtWidgets.QPushButton(self.frame_4)
        self.loginButton.setGeometry(QtCore.QRect(50, 50, 241, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.loginButton.setFont(font)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    color: rgb(170, 170, 255);\n"
"                border: 2px solid rgb(170, 170, 255);\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-size: 16px;\n"
"                font: 75 20pt \"MS Shell Dlg 2\";\n"
"                background: transparent;\n"
"            }\n"
"            QPushButton:hover {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgba(43, 171, 218, 255);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 2px solid darkblue;\n"
"                background-color: gray;\n"
"            }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/add_notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon1)
        self.loginButton.setIconSize(QtCore.QSize(48, 48))
        self.loginButton.setObjectName("loginButton")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_4)
        self.tableWidget.setGeometry(QtCore.QRect(50, 140, 991, 461))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../resources/notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Notes, icon2, "")
        self.Profile = QtWidgets.QWidget()
        self.Profile.setObjectName("Profile")
        self.frame_5 = QtWidgets.QFrame(self.Profile)
        self.frame_5.setGeometry(QtCore.QRect(-10, -10, 1101, 711))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(70, 600, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("\n"
"background: transparent; color: white; font-size: 20px;\n"
"color: rgb(170, 170, 255);")
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_15.setObjectName("label_15")

        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)

        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../resources/change_pass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(80, 140, 321, 301))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../resources/admin3.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(490, 190, 101, 51))
        self.label_5.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(490, 260, 101, 51))
        self.label_6.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.loginButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.loginButton_3.setGeometry(QtCore.QRect(830, 370, 241, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.loginButton_3.setFont(font)
        self.loginButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton_3.setStyleSheet("QPushButton {\n"
"    color: rgb(170, 170, 255);\n"
"                border: 2px solid rgb(170, 170, 255);\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-size: 16px;\n"
"                font: 75 20pt \"MS Shell Dlg 2\";\n"
"                background: transparent;\n"
"            }\n"
"            QPushButton:hover {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgba(43, 171, 218, 255);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 2px solid darkblue;\n"
"                background-color: gray;\n"
"            }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../resources/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton_3.setIcon(icon4)
        self.loginButton_3.setIconSize(QtCore.QSize(48, 48))
        self.loginButton_3.setObjectName("loginButton_3")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(620, 190, 451, 51))
        self.label_8.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(620, 260, 451, 51))
        self.label_9.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(490, 130, 161, 51))
        self.label_23.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(620, 130, 451, 51))
        self.label_24.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../resources/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.Profile, icon5, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dashboard"))
        self.label_2.setText(_translate("Form", "Total Uploaded Notes"))
        self.label_3.setText(_translate("Form", "12"))
        self.forgetButton.setText(_translate("Form", "View Details"))
        self.label_7.setText(_translate("Form", "© 2024 CodeHUB. All rights reserved."))
        self.infolabel.setText(_translate("Form", "Welcome Anoop Kumar Yadav"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dashboard), _translate("Form", "Dashboard"))
        self.label_14.setText(_translate("Form", "© 2024 CodeHUB. All rights reserved."))
        self.loginButton.setText(_translate("Form", " Add Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Notes), _translate("Form", "Notes"))
        self.label_15.setText(_translate("Form", "© 2024 CodeHUB. All rights reserved."))
        self.label_5.setText(_translate("Form", "Name   : "))
        self.label_6.setText(_translate("Form", "Email   : "))
        self.loginButton_3.setText(_translate("Form", "Logout"))
        self.label_8.setText(_translate("Form", "Anoop Kumar Yadav"))
        self.label_9.setText(_translate("Form", "anoop@gmail.com"))
        self.label_23.setText(_translate("Form", "User ID : "))
        self.label_24.setText(_translate("Form", "U51"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Profile), _translate("Form", "Profile"))
