# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'successDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_errorDialog(object):
    def setupUi(self, errorDialog):
        errorDialog.setObjectName("errorDialog")
        errorDialog.resize(639, 294)
        errorDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(errorDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 240, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(errorDialog)
        self.label.setGeometry(QtCore.QRect(30, 50, 561, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setIndent(10)
        self.label.setObjectName("label")

        self.retranslateUi(errorDialog)
        self.buttonBox.accepted.connect(errorDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(errorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(errorDialog)

    def retranslateUi(self, errorDialog):
        _translate = QtCore.QCoreApplication.translate
        errorDialog.setWindowTitle(_translate("errorDialog", " "))


class Ui_successDialog(object):
    def setupUi(self, successDialog):
        successDialog.setObjectName("successDialog")
        successDialog.resize(640, 289)
        successDialog.setWindowTitle("")
        successDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(successDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-200, 220, 801, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(successDialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 561, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setIndent(10)
        self.label.setObjectName("label")

        self.retranslateUi(successDialog)
        self.buttonBox.accepted.connect(successDialog.accept) 
        self.buttonBox.rejected.connect(successDialog.reject) 
        QtCore.QMetaObject.connectSlotsByName(successDialog)

    def retranslateUi(self, successDialog):
        pass
