# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.setFixedSize(1003, 620)
        
        font = QtGui.QFont()
        font.setPointSize(19)
        Form.setFont(font)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0681818, x2:0, y2:1, stop:0 rgba(43, 171, 218, 255), stop:0.711443 rgba(235, 103, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(560, 410, 201, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.loginButton.setFont(font)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"                border: 2px solid white;\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-size: 16px;\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"                background: transparent;\n"
"            }\n"
"            QPushButton:hover {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgba(43, 171, 218, 255);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 2px solid darkblue;\n"
"                background-color: gray;\n"
"            }")
        self.loginButton.setObjectName("loginButton")
        self.joinButton = QtWidgets.QPushButton(Form)
        self.joinButton.setGeometry(QtCore.QRect(250, 410, 201, 71))
        self.joinButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.joinButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"                border: 2px solid white;\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-size: 16px;\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"                background: transparent;\n"
"            }\n"
"            QPushButton:hover {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgba(43, 171, 218, 255);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 2px solid darkblue;\n"
"                background-color: gray;\n"
"            }")
        self.joinButton.setObjectName("joinButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 60, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"background: transparent; color: white; font-size: 80px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 490, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"background: transparent; color: white; font-size: 20px;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CodeHUB - Note Taker"))
        self.loginButton.setText(_translate("Form", "Log In"))
        self.joinButton.setText(_translate("Form", "Join"))
        self.label.setText(_translate("Form", "  CodeHUB - Note Taker "))
        self.label_2.setText(_translate("Form", "© 2024 CodeHUB. All rights reserved."))
