# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.setFixedSize(1003, 788)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(19)
        Form.setFont(font)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.0681818, x2:0, y2:1, stop:0 rgba(43, 171, 218, 255), stop:0.711443 rgba(235, 103, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.fignupButton = QtWidgets.QPushButton(Form)
        self.fignupButton.setGeometry(QtCore.QRect(400, 580, 201, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.fignupButton.setFont(font)
        self.fignupButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fignupButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"                border: 2px solid white;\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                font-size: 16px;\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"                background: transparent;\n"
"            }\n"
"            QPushButton:hover {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgba(43, 171, 218, 255);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 2px solid darkblue;\n"
"                background-color: gray;\n"
"            }")
        self.fignupButton.setObjectName("fignupButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"background: transparent; color: white; font-size: 80px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 670, 991, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"background: transparent; color: white; font-size: 20px;")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.fullNameText = QtWidgets.QLineEdit(Form)
        self.fullNameText.setGeometry(QtCore.QRect(270, 230, 481, 51))
        self.fullNameText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 169, 219);")
        self.fullNameText.setText("")
        self.fullNameText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fullNameText.setObjectName("fullNameText")
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(410, 540, 191, 28))
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.loginButton.setStyleSheet("\n"
"QPushButton {\n"
"background-color: transparent;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"            }\n"
"            QPushButton:hover {\n"
"           color: rgb(0, 255, 127);\n"
"            }")
        self.loginButton.setObjectName("loginButton")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(-20, -10, 201, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setStyleSheet("QPushButton {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgba(43, 171, 218, 255);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"                border-radius: 20px;\n"
"                padding: 5px;\n"
"                font-size: 16px;\n"
"                font: 75 20pt \"MS Shell Dlg 2\";\n"
"            }\n"
"            QPushButton:hover {\n"
"                border: 2px solid rgba(43, 171, 218, 255);\n"
"                color:rgb(232, 104, 254);\n"
"                background-color: rgba(255, 255, 255, 255);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                border: 2px solid darkblue;\n"
"                background-color: gray;\n"
"            }")
        self.backButton.setObjectName("backButton")
        self.emailText = QtWidgets.QLineEdit(Form)
        self.emailText.setGeometry(QtCore.QRect(270, 290, 481, 51))
        self.emailText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 169, 219);")
        self.emailText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.emailText.setObjectName("emailText")
        self.passText = QtWidgets.QLineEdit(Form)
        self.passText.setGeometry(QtCore.QRect(270, 380, 481, 51))
        self.passText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 169, 219);")
        self.passText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passText.setObjectName("passText")
        self.repassText = QtWidgets.QLineEdit(Form)
        self.repassText.setGeometry(QtCore.QRect(270, 440, 481, 51))
        self.repassText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(48, 169, 219);")
        self.repassText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.repassText.setObjectName("repassText")
        self.passErrorLabel = QtWidgets.QLabel(Form)
        self.passErrorLabel.setGeometry(QtCore.QRect(270, 510, 481, 21))
        self.passErrorLabel.setStyleSheet("background:transparent;\n"
"color: rgb(255, 0, 0);")
        self.passErrorLabel.setText("")
        self.passErrorLabel.setObjectName("passErrorLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Register"))
        self.fignupButton.setText(_translate("Form", "Sign Up"))
        self.label.setText(_translate("Form", "Sign Up"))
        self.label_2.setText(_translate("Form", "© 2024 CodeHUB. All rights reserved."))
        self.fullNameText.setPlaceholderText(_translate("Form", "  Full Name"))
        self.loginButton.setText(_translate("Form", "Login ->"))
        self.backButton.setText(_translate("Form", "Back"))
        self.emailText.setPlaceholderText(_translate("Form", "  Email "))
        self.passText.setPlaceholderText(_translate("Form", "   Enter Password"))
        self.repassText.setPlaceholderText(_translate("Form", "   Repeat- Password"))
